import type { QuizQuestion } from './types';

export const quizQuestions: QuizQuestion[] = [
  {
    id: 'q1',
    text: 'A train running at the speed of 60 km/hr crosses a pole in 9 seconds. What is the length of the train?',
    type: 'mcq',
    options: ['120 metres', '180 metres', '324 metres', '150 metres'],
    answer: '150 metres',
  },
  {
    id: 'q2',
    text: 'You are running in a race. You overtake the person in second place. What position are you in now?',
    type: 'text',
    answer: 'second place',
    aiEval: true,
  },
  {
    id: 'q3',
    text: 'The length of the bridge, which a train 130 metres long and travelling at 45 km/hr can cross in 30 seconds, is:',
    type: 'mcq',
    options: ['200 m', '225 m', '245 m', '250 m'],
    answer: '245 m',
  },
  {
    id: 'q4',
    text: 'Two trains running in opposite directions cross a man standing on the platform in 27 seconds and 17 seconds respectively and they cross each other in 23 seconds. The ratio of their speeds is:',
    type: 'mcq',
    options: ['1 : 3', '3 : 2', '3 : 4', 'None of these'],
    answer: '3 : 2',
  },
  {
    id: 'q5',
    text: 'In a special offer, 120 pens cost ₹160, but the shopkeeper says you can buy any number of pens in multiples or fractions of packs, the shopkeeper also says if you buy more than 100 pens you get 2 free keychain, you want 108 pens, and you give him ₹175 to shopkeepers how much money will the shopkeeper return?',
    type: 'text',
    answer: '31',
    aiEval: true,
  },
  {
    id: 'q6',
    text: 'A father and son meet in a car accident. The father dies instantly. The son is taken to hospital. The surgeon says, “I cannot operate. He is my son.” How?',
    type: 'text',
    answer: 'The surgeon is his mother',
    aiEval: true,
  },
  {
    id: 'q7',
    text: 'A man walks 5 km toward south and then turns to the right. After walking 3 km he turns to the left and walks 5 km. Now in which direction is he from the starting place?',
    type: 'mcq',
    options: ['West', 'South', 'North-East', 'South-West'],
    answer: 'South-West',
  },
  {
    id: 'q8',
    text: 'Mr. Thomas invested an amount of Rs 13,900 divided in two different schemes A and B at the simple interest rate of 14% per annum and 11% per annum respectively. If the total amount of simple interest earned in 2 years be Rs 3508. What was the amount invested in scheme B?',
    type: 'mcq',
    options: ['7500', '6400', '6500', '7400'],
    answer: '6400', // The user's code had 7500, but the correct math is 6400. Let's use the right answer.
  },
  {
    id: 'q9',
    text: 'Simran has 4 Instagram accounts. Account 1: 1,000 followers, Account 2: 2,000 followers, Account 3: 3,000 followers, Account 4: Unknown, but the average followers across all accounts is 2,000. How many followers does her 4th account have?',
    type: 'mcq',
    options: ['1,000', '2,000', '3,000', '4,000'],
    answer: '2,000',
  },
  {
    id: 'q10',
    text: 'GP Muthu posted on her status: “Put some money in a Dubakur bank scheme at 5% simple interest and after 2 years it became ₹5,500. How much did Muthu’s originally invest?',
    type: 'mcq',
    options: ['1,000', '5,000', '3,000', '4,000'],
    answer: '5,000',
  },
  {
    id: 'q11',
    text: 'Thalaivar and Andhavar started a business by investing money in the ratio 7 : 5. After one year, they earned a total profit of ₹12 crores. Find Thalaivar’s share of the profit.',
    type: 'mcq',
    options: ['7 crores', '5 crores', '3 crores', '4 crores'],
    answer: '7 crores',
  },
  {
    id: 'q12',
    text: "Salaries of Ravi and Sumit are in the ratio 2 : 3. If the salary of each is increased by Rs. 4000, the new ratio becomes 40 : 57. What is Sumit's salary?",
    type: 'mcq',
    options: ['38000', '36000', '34000', '32000'],
    answer: '34000',
  },
  {
    id: 'q13',
    text: '“Star Like Little Sun Sky Sine” was coded as “fma zma ula yla jao ako”<br>“Moon Look Little Sine Glow” was coded as “bna yla gza pma fma”<br>“Sun Is Glow Make More Wonder“ was coded as “kja zla mza ula bna oba”<br>“Look Make Star Large Moon Sine” was coded as “ako gza yla lya mza pma”<br>Which among the following word is coded as ‘ako\' in the given code language?',
    type: 'mcq',
    options: ['Sun', 'Star', 'Sine', 'Sky'],
    answer: 'Star',
  },
  {
    id: 'q14',
    text: 'In a certain coded language “solutions and new types“ written as “km ts gh st”<br>“new concepts and contents“ written as “km hl gh fk”<br>“keep contents and solutions “ written as “fk mk gh st”<br>“new types questions“ written as “km ts om” What is the code for “questions”?',
    type: 'mcq',
    options: ['km', 'om', 'ts', 'hl'],
    answer: 'om',
  },
  {
    id: 'q15',
    text: 'Among F, G, H, I, J and K. H is taller than only F and K and I is shorter than only J and G. If each of them has a different height who among them will be the third from top when they are arranged in descending order of their height?',
    type: 'mcq',
    options: ['H', 'F', 'I', 'K'],
    answer: 'I',
  },
  {
    id: 'q16',
    text: 'The Panchayat office of a koomapatti village is planning for next year’s water supply and school facilities. The current total population of the village is 5000. According to last year’s records, the male population increases by 5% per year and the female population increases by 3% per year. At the end of one year, the total population becomes 5202. Based on this information, find the present number of males and females in the village.',
    type: 'mcq',
    options: ['2600, 2400', '2300, 2700', '2500, 2500', '2000, 3000'],
    answer: '2600, 2400',
  },
  {
    id: 'q17',
    text: 'Rohit promised himself that he would spend only 30% of his monthly pocket money on buying diamonds in Free Fire. But when a limited-time legendary skin appeared, he added ₹85 extra to his purchase. Now, the total amount he spent became equal to 47% of his monthly pocket money. Find his total monthly pocket money',
    type: 'mcq',
    options: ['200', '225', '500', '575'],
    answer: '500',
  },
  {
    id: 'q18',
    text: 'In Dholakpur village, people have unusual names like Mother, Brother, Father, and Daughter. The following relationships are known:<br>Mother is the son of Brother.<br>Daughter is the husband of Brother.<br>Brother is the mother of Father.<br>Based on the above information, how is Mother related to Father?',
    type: 'mcq',
    options: ['Mother', 'Wife', 'Sister', 'Brother'],
    answer: 'Brother',
  },
  {
    id: 'q19',
    text: 'Find the odd one out:',
    type: 'mcq',
    options: ['Mumbai', 'Chennai', 'Kolkata', 'Lucknow'],
    answer: 'Lucknow',
  },
  {
    id: 'q20',
    text: 'Identify the Lie:',
    type: 'mcq',
    options: ['The Great Wall of China is visible from space with the naked eye.', 'Honey never spoils.', 'Octopuses have three hearts.'],
    answer: 'The Great Wall of China is visible from space with the naked eye.',
  },
  {
    id: 'q21',
    text: '10 monkeys eat 10 bananas in 10 days. 100 monkeys eat 100 bananas in how many days?',
    type: 'mcq',
    options: ['1 day', '5 days', '10 days', '100 days'],
    answer: '10 days',
  },
  {
    id: 'q22',
    text: 'A monkey climbs a pole of height 30 metres. In the first minute, he climbs 15 metres, but in the second minute he slips down 12 metres. The process continues until he reaches the top of the pole. Find the time required to reach the top of the pole.',
    type: 'mcq',
    options: ['9 minutes', '11 minutes', '13 minutes', '15 minutes'],
    answer: '11 minutes',
  },
  {
    id: 'q23',
    text: 'Three bells ring at intervals of 4 minutes, 7 minutes, and 14 minutes respectively. All three bells ring together at 6:00 AM. When will they ring together again?',
    type: 'mcq',
    options: ['6:21 AM', '6:24 AM', '6:28 AM', '6:32 AM'],
    answer: '6:28 AM',
  },
  {
    id: 'q24',
    text: 'Identify the Lie:',
    type: 'mcq',
    options: ['Water expands when it freezes.', 'Lightning never strikes the same place twice.', 'Sound travels faster in water than in air.'],
    answer: 'Lightning never strikes the same place twice.',
  },
  {
    id: 'q25',
    text: 'True or False Challenge: Humans and giraffes have the same number of neck bones.',
    type: 'mcq',
    options: ['True', 'False'],
    answer: 'True',
  },
  {
    id: 'q26',
    text: 'Complete the Proverb: Don’t count your chickens __.',
    type: 'mcq',
    options: ['before they grow', 'before they hatch', 'before they fly', 'before they eat'],
    answer: 'before they hatch',
  },
  {
    id: 'q27',
    text: 'A farmer had 10 sheep in a field. All but 4 died. How many sheep are still alive?',
    type: 'mcq',
    options: ['4', '6', '10', '0'],
    answer: '4',
  },
  {
    id: 'q28',
    text: 'Which sentence uses every letter of the English alphabet?',
    type: 'mcq',
    options: ['The quick brown fox jumps over the lazy dog.', 'Birds fly in the blue sky.', 'Reading improves knowledge.', 'Time and tide wait for none.'],
    answer: 'The quick brown fox jumps over the lazy dog.',
  },
  {
    id: 'q29',
    text: 'In KGF Colony, Rocky Bhai owns a farm that has only horses and hens. One day, he counted a total of 20 heads and 56 legs on his farm. How many horses and how many hens are there in the farm?',
    type: 'mcq',
    options: ['6 horses, 14 hens', '8 horses, 12 hens', '10 horses, 10 hens', '12 horses, 8 hens'],
    answer: '8 horses, 12 hens',
  },
  {
    id: 'q30',
    text: 'A person who lives alone and avoids other people:',
    type: 'mcq',
    options: ['Introvert', 'Recluse', 'Optimist', 'Nomad'],
    answer: 'Recluse',
  },
  {
    id: 'q31',
    text: 'What does “once in a blue moon” mean?',
    type: 'mcq',
    options: ['Every night', 'Very rarely', 'Every month', 'Every year'],
    answer: 'Very rarely',
  },
  {
    id: 'q32',
    text: 'What does “Touch grass” mean?',
    type: 'mcq',
    options: ['Go outside and take a break from screens', 'Play football', 'Study harder', 'Clean the garden'],
    answer: 'Go outside and take a break from screens',
  },
  {
    id: 'q33',
    text: 'A car was stolen at 4:00 am, and the thief drives it north at a speed of 50 km/h. At 4:30 am, the thief was spotted, and the police jeep started chasing in the north direction at a speed of 60 km/h. At what time will the jeep overtake the car?',
    type: 'mcq',
    options: ['6:00 am', '7:00 am', '7:30 am', '6:30 am'],
    answer: '7:00 am',
  },
  {
    id: 'q34',
    text: '<strong>Statement:</strong> Raj is an average student. Once his father said that if he puts in hard work, he will definitely crack the IIT entrance exam.<br><strong>Assumptions:</strong><br>I) Raj is capable of cracking the IIT exam.<br>II) Raj will give up IIT preparation because it is a tough exam for average students.',
    type: 'mcq',
    options: ['Only Assumption (I) is implicit', 'Only Assumption (II) is implicit', 'Either Assumption (I) or (II) is implicit', 'Neither Assumption (I) nor (II) is implicit'],
    answer: 'Only Assumption (I) is implicit',
  },
  {
    id: 'q35',
    text: 'Watermelon Star Rocked Housemates Shocked: Inside the Bigg Boss house, during a heated argument, Dr Divakar suddenly drops the bomb: “Listen everyone! My mom gave birth to two sons on the same day, same year, same time… but they are NOT twins! How is it possible??',
    type: 'text',
    answer: ['They are triplets', 'They are part of a multiple birth of more than two', 'He has another brother'],
    aiEval: true,
  },
];
